create extension if not exists pgcrypto;

create table public.community_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null check (char_length(display_name) between 2 and 40),
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.shikigami_reviews (
  id bigint generated by default as identity primary key,
  shikigami_id integer not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  category text not null default 'overall' check (category in ('overall', 'pve', 'pvp', 'beginner')),
  rating smallint not null check (rating between 1 and 5),
  content text not null check (char_length(content) between 10 and 2000),
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected', 'hidden')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (shikigami_id, user_id, category)
);

create table public.soul_recommendations (
  id bigint generated by default as identity primary key,
  shikigami_id integer not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  primary_soul_id integer not null,
  secondary_soul_id integer,
  slot_2_stat text,
  slot_4_stat text,
  slot_6_stat text,
  note text check (note is null or char_length(note) <= 1000),
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected', 'hidden')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (shikigami_id, user_id, primary_soul_id, secondary_soul_id)
);

create table public.review_votes (
  review_id bigint not null references public.shikigami_reviews(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (review_id, user_id)
);

create table public.recommendation_votes (
  recommendation_id bigint not null references public.soul_recommendations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (recommendation_id, user_id)
);

create table public.community_reports (
  id bigint generated by default as identity primary key,
  reporter_id uuid not null references auth.users(id) on delete cascade,
  target_type text not null check (target_type in ('review', 'soul_recommendation')),
  target_id bigint not null,
  reason text not null check (char_length(reason) between 5 and 500),
  status text not null default 'pending' check (status in ('pending', 'resolved', 'dismissed')),
  created_at timestamptz not null default now(),
  unique (reporter_id, target_type, target_id)
);

create index shikigami_reviews_public_idx on public.shikigami_reviews (shikigami_id, status, created_at desc);
create index soul_recommendations_public_idx on public.soul_recommendations (shikigami_id, status, created_at desc);
create index review_votes_review_idx on public.review_votes (review_id);
create index recommendation_votes_recommendation_idx on public.recommendation_votes (recommendation_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger community_profiles_updated_at before update on public.community_profiles
for each row execute function public.set_updated_at();
create trigger shikigami_reviews_updated_at before update on public.shikigami_reviews
for each row execute function public.set_updated_at();
create trigger soul_recommendations_updated_at before update on public.soul_recommendations
for each row execute function public.set_updated_at();

alter table public.community_profiles enable row level security;
alter table public.shikigami_reviews enable row level security;
alter table public.soul_recommendations enable row level security;
alter table public.review_votes enable row level security;
alter table public.recommendation_votes enable row level security;
alter table public.community_reports enable row level security;

revoke all on table public.community_profiles from anon, authenticated;
revoke all on table public.shikigami_reviews from anon, authenticated;
revoke all on table public.soul_recommendations from anon, authenticated;
revoke all on table public.review_votes from anon, authenticated;
revoke all on table public.recommendation_votes from anon, authenticated;
revoke all on table public.community_reports from anon, authenticated;

grant select on public.community_profiles to anon, authenticated;
grant select on public.shikigami_reviews to anon, authenticated;
grant select on public.soul_recommendations to anon, authenticated;
grant select on public.review_votes to anon, authenticated;
grant select on public.recommendation_votes to anon, authenticated;
grant insert, update on public.community_profiles to authenticated;
grant insert, update, delete on public.shikigami_reviews to authenticated;
grant insert, update, delete on public.soul_recommendations to authenticated;
grant insert, delete on public.review_votes to authenticated;
grant insert, delete on public.recommendation_votes to authenticated;
grant insert on public.community_reports to authenticated;
grant usage, select on all sequences in schema public to authenticated;

create policy "profiles are public" on public.community_profiles
for select to anon, authenticated using (true);
create policy "users create own profile" on public.community_profiles
for insert to authenticated with check ((select auth.uid()) = id);
create policy "users update own profile" on public.community_profiles
for update to authenticated using ((select auth.uid()) = id) with check ((select auth.uid()) = id);

create policy "approved reviews are public" on public.shikigami_reviews
for select to anon, authenticated using (status = 'approved' or (select auth.uid()) = user_id);
create policy "users submit own reviews" on public.shikigami_reviews
for insert to authenticated with check ((select auth.uid()) = user_id and status = 'pending');
create policy "users edit own pending reviews" on public.shikigami_reviews
for update to authenticated using ((select auth.uid()) = user_id and status = 'pending')
with check ((select auth.uid()) = user_id and status = 'pending');
create policy "users delete own pending reviews" on public.shikigami_reviews
for delete to authenticated using ((select auth.uid()) = user_id and status = 'pending');

create policy "approved recommendations are public" on public.soul_recommendations
for select to anon, authenticated using (status = 'approved' or (select auth.uid()) = user_id);
create policy "users submit own recommendations" on public.soul_recommendations
for insert to authenticated with check ((select auth.uid()) = user_id and status = 'pending');
create policy "users edit own pending recommendations" on public.soul_recommendations
for update to authenticated using ((select auth.uid()) = user_id and status = 'pending')
with check ((select auth.uid()) = user_id and status = 'pending');
create policy "users delete own pending recommendations" on public.soul_recommendations
for delete to authenticated using ((select auth.uid()) = user_id and status = 'pending');

create policy "review votes are public" on public.review_votes
for select to anon, authenticated using (true);
create policy "users vote once per review" on public.review_votes
for insert to authenticated with check (
  (select auth.uid()) = user_id and exists (
    select 1 from public.shikigami_reviews r where r.id = review_id and r.status = 'approved'
  )
);
create policy "users remove own review vote" on public.review_votes
for delete to authenticated using ((select auth.uid()) = user_id);

create policy "recommendation votes are public" on public.recommendation_votes
for select to anon, authenticated using (true);
create policy "users vote once per recommendation" on public.recommendation_votes
for insert to authenticated with check (
  (select auth.uid()) = user_id and exists (
    select 1 from public.soul_recommendations r where r.id = recommendation_id and r.status = 'approved'
  )
);
create policy "users remove own recommendation vote" on public.recommendation_votes
for delete to authenticated using ((select auth.uid()) = user_id);

create policy "users submit reports" on public.community_reports
for insert to authenticated with check ((select auth.uid()) = reporter_id and status = 'pending');
