create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.official_review_reports (
  id bigint generated by default as identity primary key,
  shikigami_id integer not null,
  note text not null check (char_length(trim(note)) between 1 and 300),
  reporter_hash text not null,
  status text not null default 'pending' check (status in ('pending', 'resolved', 'dismissed')),
  created_at timestamptz not null default now(),
  unique (shikigami_id, reporter_hash)
);

alter table public.admin_users enable row level security;
revoke all on public.admin_users from anon, authenticated;
alter table public.official_review_reports enable row level security;
revoke all on public.official_review_reports from anon, authenticated;

create table if not exists public.admin_moderation_log (
  id bigint generated by default as identity primary key,
  admin_user_id uuid not null references auth.users(id) on delete restrict,
  target_kind text not null,
  target_id bigint not null,
  action text not null,
  created_at timestamptz not null default now()
);
alter table public.admin_moderation_log enable row level security;
revoke all on public.admin_moderation_log from anon, authenticated;

create or replace function public.is_community_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (select 1 from public.admin_users where user_id = (select auth.uid()));
$$;

create or replace function public.admin_moderation_data()
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare result jsonb;
begin
  if not public.is_community_admin() then raise exception 'Bạn không có quyền quản trị.'; end if;

  select jsonb_build_object(
    'recommendations', coalesce((select jsonb_agg(to_jsonb(r) order by r.created_at desc) from (select * from public.soul_recommendations order by created_at desc limit 500) r), '[]'::jsonb),
    'reviews', coalesce((select jsonb_agg(to_jsonb(r) order by r.created_at desc) from (select * from public.shikigami_reviews order by created_at desc limit 500) r), '[]'::jsonb),
    'reports', coalesce((select jsonb_agg(to_jsonb(r) order by r.created_at desc) from (select id, shikigami_id, note, status, created_at from public.official_review_reports order by created_at desc limit 500) r), '[]'::jsonb)
  ) into result;
  return result;
end;
$$;

create or replace function public.admin_moderate_item(p_kind text, p_id bigint, p_action text)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not public.is_community_admin() then raise exception 'Bạn không có quyền quản trị.'; end if;

  if p_kind = 'recommendation' then
    if p_action = 'delete' then delete from public.soul_recommendations where id = p_id;
    elsif p_action in ('approved', 'rejected', 'hidden') then update public.soul_recommendations set status = p_action, updated_at = now() where id = p_id;
    else raise exception 'Thao tác không hợp lệ.'; end if;
  elsif p_kind = 'review' then
    if p_action = 'delete' then delete from public.shikigami_reviews where id = p_id;
    elsif p_action in ('approved', 'rejected', 'hidden') then update public.shikigami_reviews set status = p_action, updated_at = now() where id = p_id;
    else raise exception 'Thao tác không hợp lệ.'; end if;
  elsif p_kind = 'report' then
    if p_action = 'delete' then delete from public.official_review_reports where id = p_id;
    elsif p_action in ('pending', 'resolved', 'dismissed') then update public.official_review_reports set status = p_action where id = p_id;
    else raise exception 'Thao tác không hợp lệ.'; end if;
  else
    raise exception 'Loại dữ liệu không hợp lệ.';
  end if;
  insert into public.admin_moderation_log (admin_user_id, target_kind, target_id, action)
  values ((select auth.uid()), p_kind, p_id, p_action);
  return found;
end;
$$;

revoke all on function public.is_community_admin() from public;
revoke all on function public.admin_moderation_data() from public;
revoke all on function public.admin_moderate_item(text, bigint, text) from public;
revoke all on function public.is_community_admin() from anon;
revoke all on function public.admin_moderation_data() from anon;
revoke all on function public.admin_moderate_item(text, bigint, text) from anon;
grant execute on function public.is_community_admin() to authenticated;
grant execute on function public.admin_moderation_data() to authenticated;
grant execute on function public.admin_moderate_item(text, bigint, text) to authenticated;

-- Sau khi tạo tài khoản trong Supabase Authentication, chạy một lần:
-- insert into public.admin_users (user_id)
-- select id from auth.users where email = 'EMAIL_QUAN_TRI_CUA_BAN';
