create extension if not exists pgcrypto with schema extensions;

create table if not exists public.skill_description_reports (
  id bigint generated by default as identity primary key,
  shikigami_id integer not null,
  skill_id text not null,
  skill_name text not null check (char_length(trim(skill_name)) between 1 and 200),
  note text not null check (char_length(trim(note)) between 1 and 300),
  reporter_hash text not null,
  status text not null default 'pending' check (status in ('pending', 'resolved', 'dismissed')),
  created_at timestamptz not null default now(),
  unique (shikigami_id, skill_id, reporter_hash)
);

alter table public.skill_description_reports enable row level security;
revoke all on public.skill_description_reports from anon, authenticated;

create or replace function public.report_skill_description(p_shikigami_id integer, p_skill_id text, p_skill_name text, p_note text)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  headers jsonb := coalesce(nullif(current_setting('request.headers', true), ''), '{}')::jsonb;
  visitor_ip text;
  visitor_hash text;
begin
  if p_shikigami_id <= 0 then raise exception 'Thức thần không hợp lệ.'; end if;
  if char_length(trim(coalesce(p_skill_id, ''))) not between 1 and 100 then raise exception 'Kỹ năng không hợp lệ.'; end if;
  if char_length(trim(coalesce(p_skill_name, ''))) not between 1 and 200 then raise exception 'Tên kỹ năng không hợp lệ.'; end if;
  if char_length(trim(coalesce(p_note, ''))) not between 1 and 300 then raise exception 'Ghi chú phải có từ 1 đến 300 ký tự.'; end if;
  visitor_ip := coalesce(nullif(headers ->> 'cf-connecting-ip', ''), nullif(split_part(headers ->> 'x-forwarded-for', ',', 1), ''), nullif(headers ->> 'x-real-ip', ''));
  if visitor_ip is null then raise exception 'Không xác định được địa chỉ người dùng.'; end if;
  visitor_hash := encode(extensions.digest(trim(visitor_ip) || ':onmyoji-skill-description-report-v1', 'sha256'), 'hex');

  insert into public.skill_description_reports (shikigami_id, skill_id, skill_name, note, reporter_hash)
  values (p_shikigami_id, trim(p_skill_id), trim(p_skill_name), trim(p_note), visitor_hash)
  on conflict (shikigami_id, skill_id, reporter_hash)
  do update set skill_name = excluded.skill_name, note = excluded.note, status = 'pending', created_at = now();
  return true;
end;
$$;

grant execute on function public.report_skill_description(integer, text, text, text) to anon, authenticated;

create or replace function public.admin_moderation_data()
returns jsonb language plpgsql security definer set search_path = '' as $$
declare result jsonb;
begin
  if not public.is_community_admin() then raise exception 'Bạn không có quyền quản trị.'; end if;
  select jsonb_build_object(
    'recommendations', coalesce((select jsonb_agg(to_jsonb(r) order by r.created_at desc) from (select * from public.soul_recommendations order by created_at desc limit 500) r), '[]'::jsonb),
    'reviews', coalesce((select jsonb_agg(to_jsonb(r) order by r.created_at desc) from (select * from public.shikigami_reviews order by created_at desc limit 500) r), '[]'::jsonb),
    'reports', coalesce((select jsonb_agg(to_jsonb(r) order by r.created_at desc) from (select id, shikigami_id, note, status, created_at from public.official_review_reports order by created_at desc limit 500) r), '[]'::jsonb),
    'skill_reports', coalesce((select jsonb_agg(to_jsonb(r) order by r.created_at desc) from (select id, shikigami_id, skill_id, skill_name, note, status, created_at from public.skill_description_reports order by created_at desc limit 500) r), '[]'::jsonb)
  ) into result;
  return result;
end;
$$;

create or replace function public.admin_moderate_item(p_kind text, p_id bigint, p_action text)
returns boolean language plpgsql security definer set search_path = '' as $$
begin
  if not public.is_community_admin() then raise exception 'Bạn không có quyền quản trị.'; end if;
  if p_kind = 'recommendation' then
    if p_action = 'delete' then delete from public.soul_recommendations where id = p_id;
    elsif p_action in ('approved', 'rejected', 'hidden') then update public.soul_recommendations set status = p_action, updated_at = now() where id = p_id;
    else raise exception 'Thao tác không hợp lệ.'; end if;
  elsif p_kind = 'review' then
    if p_action = 'delete' then delete from public.shikigami_reviews where id = p_id;
    elsif p_action in ('approved', 'rejected', 'hidden') then update public.shikigami_reviews set status = p_action, updated_at = now() where id = p_id;
    else raise exception 'Thao tác không hợp lệ.'; end if;
  elsif p_kind = 'report' then
    if p_action = 'delete' then delete from public.official_review_reports where id = p_id;
    elsif p_action in ('pending', 'resolved', 'dismissed') then update public.official_review_reports set status = p_action where id = p_id;
    else raise exception 'Thao tác không hợp lệ.'; end if;
  elsif p_kind = 'skill_report' then
    if p_action = 'delete' then delete from public.skill_description_reports where id = p_id;
    elsif p_action in ('pending', 'resolved', 'dismissed') then update public.skill_description_reports set status = p_action where id = p_id;
    else raise exception 'Thao tác không hợp lệ.'; end if;
  else raise exception 'Loại dữ liệu không hợp lệ.';
  end if;
  insert into public.admin_moderation_log (admin_user_id, target_kind, target_id, action) values ((select auth.uid()), p_kind, p_id, p_action);
  return found;
end;
$$;

revoke all on function public.report_skill_description(integer, text, text, text) from public;
grant execute on function public.report_skill_description(integer, text, text, text) to anon, authenticated;
revoke all on function public.admin_moderation_data() from public;
revoke all on function public.admin_moderate_item(text, bigint, text) from public;
grant execute on function public.admin_moderation_data() to authenticated;
grant execute on function public.admin_moderate_item(text, bigint, text) to authenticated;
