create extension if not exists pgcrypto with schema extensions;

create table if not exists public.soul_recommendation_likes (
  id bigint generated by default as identity primary key,
  shikigami_id integer not null,
  mode text not null check (mode in ('basic', 'pvp')),
  primary_soul_id integer not null,
  voter_hash text not null,
  created_at timestamptz not null default now(),
  unique (shikigami_id, mode, primary_soul_id, voter_hash)
);

alter table public.soul_recommendation_likes enable row level security;
revoke all on public.soul_recommendation_likes from anon, authenticated;

create or replace function public.soul_like_visitor_hash()
returns text
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  headers jsonb := coalesce(nullif(current_setting('request.headers', true), ''), '{}')::jsonb;
  visitor_ip text;
begin
  visitor_ip := coalesce(
    nullif(headers ->> 'cf-connecting-ip', ''),
    nullif(split_part(headers ->> 'x-forwarded-for', ',', 1), ''),
    nullif(headers ->> 'x-real-ip', '')
  );
  if visitor_ip is null then
    raise exception 'Không xác định được địa chỉ người dùng.';
  end if;
  return encode(extensions.digest(trim(visitor_ip) || ':onmyoji-soul-like-v1', 'sha256'), 'hex');
end;
$$;

create or replace function public.like_soul_recommendation(
  p_shikigami_id integer,
  p_mode text,
  p_primary_soul_id integer
)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  inserted_count integer;
begin
  if p_mode not in ('basic', 'pvp') then raise exception 'Chế độ không hợp lệ.'; end if;
  if not exists (
    select 1 from public.soul_recommendations
    where shikigami_id = p_shikigami_id
      and mode = p_mode
      and primary_soul_id = p_primary_soul_id
      and status = 'approved'
  ) then raise exception 'Đề xuất chưa được duyệt.'; end if;

  insert into public.soul_recommendation_likes (shikigami_id, mode, primary_soul_id, voter_hash)
  values (p_shikigami_id, p_mode, p_primary_soul_id, public.soul_like_visitor_hash())
  on conflict do nothing;
  get diagnostics inserted_count = row_count;
  return inserted_count = 1;
end;
$$;

create or replace function public.get_soul_recommendation_likes(
  p_shikigami_id integer,
  p_mode text
)
returns table (primary_soul_id integer, like_count bigint, viewer_liked boolean)
language sql
security definer
set search_path = public, extensions
as $$
  select l.primary_soul_id,
         count(*)::bigint as like_count,
         bool_or(l.voter_hash = public.soul_like_visitor_hash()) as viewer_liked
  from public.soul_recommendation_likes l
  where l.shikigami_id = p_shikigami_id and l.mode = p_mode
  group by l.primary_soul_id;
$$;

revoke all on function public.soul_like_visitor_hash() from public;
grant execute on function public.like_soul_recommendation(integer, text, integer) to anon, authenticated;
grant execute on function public.get_soul_recommendation_likes(integer, text) to anon, authenticated;
