create extension if not exists pgcrypto with schema extensions;

create table if not exists public.official_review_reports (
  id bigint generated by default as identity primary key,
  shikigami_id integer not null,
  note text not null check (char_length(trim(note)) between 1 and 300),
  reporter_hash text not null,
  status text not null default 'pending' check (status in ('pending', 'resolved', 'dismissed')),
  created_at timestamptz not null default now(),
  unique (shikigami_id, reporter_hash)
);

alter table public.official_review_reports enable row level security;
revoke all on public.official_review_reports from anon, authenticated;

create or replace function public.report_official_shikigami_review(p_shikigami_id integer, p_note text)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  headers jsonb := coalesce(nullif(current_setting('request.headers', true), ''), '{}')::jsonb;
  visitor_ip text;
  visitor_hash text;
begin
  if p_shikigami_id <= 0 then raise exception 'Thức thần không hợp lệ.'; end if;
  if char_length(trim(coalesce(p_note, ''))) not between 1 and 300 then raise exception 'Ghi chú phải có từ 1 đến 300 ký tự.'; end if;
  visitor_ip := coalesce(
    nullif(headers ->> 'cf-connecting-ip', ''),
    nullif(split_part(headers ->> 'x-forwarded-for', ',', 1), ''),
    nullif(headers ->> 'x-real-ip', '')
  );
  if visitor_ip is null then raise exception 'Không xác định được địa chỉ người dùng.'; end if;
  visitor_hash := encode(extensions.digest(trim(visitor_ip) || ':onmyoji-official-review-report-v1', 'sha256'), 'hex');

  insert into public.official_review_reports (shikigami_id, note, reporter_hash)
  values (p_shikigami_id, trim(p_note), visitor_hash)
  on conflict (shikigami_id, reporter_hash)
  do update set note = excluded.note, status = 'pending', created_at = now();
  return true;
end;
$$;

grant execute on function public.report_official_shikigami_review(integer, text) to anon, authenticated;
