create extension if not exists pgcrypto with schema extensions;

-- Keep this migration self-contained in case the review-detail migration was not run.
alter table public.shikigami_reviews
  alter column user_id drop not null,
  alter column rating drop not null,
  alter column content drop not null;

alter table public.shikigami_reviews
  add column if not exists reviewer_name text,
  add column if not exists verdict text,
  add column if not exists summary text,
  add column if not exists pve_short_score numeric(3,1),
  add column if not exists pve_short_note text,
  add column if not exists pve_long_score numeric(3,1),
  add column if not exists pve_long_note text,
  add column if not exists pvp_score numeric(3,1),
  add column if not exists pvp_note text,
  add column if not exists beginner_score numeric(3,1),
  add column if not exists beginner_note text,
  add column if not exists strengths text,
  add column if not exists weaknesses text,
  add column if not exists pve_review text,
  add column if not exists pvp_review text,
  add column if not exists soul_recommendations text;

alter table public.shikigami_reviews drop constraint if exists shikigami_reviews_shikigami_id_user_id_category_key;
alter table public.shikigami_reviews drop constraint if exists shikigami_reviews_rating_check;
alter table public.shikigami_reviews drop constraint if exists shikigami_reviews_content_check;
alter table public.shikigami_reviews drop constraint if exists community_review_name_length;
alter table public.shikigami_reviews drop constraint if exists community_review_verdict_length;
alter table public.shikigami_reviews drop constraint if exists community_review_scores;
alter table public.shikigami_reviews add constraint shikigami_reviews_rating_check check (rating is null or rating between 1 and 5);
alter table public.shikigami_reviews add constraint community_review_name_length check (reviewer_name is null or char_length(reviewer_name) between 2 and 50);
alter table public.shikigami_reviews add constraint community_review_verdict_length check (verdict is null or char_length(verdict) between 3 and 1000);
alter table public.shikigami_reviews add constraint community_review_scores check (
  (pve_short_score is null or pve_short_score between 0 and 10) and
  (pve_long_score is null or pve_long_score between 0 and 10) and
  (pvp_score is null or pvp_score between 0 and 10) and
  (beginner_score is null or beginner_score between 0 and 10)
);

grant insert on public.shikigami_reviews to anon;
grant usage, select on all sequences in schema public to anon;

create table if not exists public.shikigami_review_likes (
  id bigint generated by default as identity primary key,
  review_id bigint not null references public.shikigami_reviews(id) on delete cascade,
  voter_hash text not null,
  created_at timestamptz not null default now(),
  unique (review_id, voter_hash)
);

alter table public.shikigami_review_likes enable row level security;
revoke all on public.shikigami_review_likes from anon, authenticated;

create or replace function public.review_like_visitor_hash()
returns text
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  headers jsonb := coalesce(nullif(current_setting('request.headers', true), ''), '{}')::jsonb;
  visitor_ip text;
begin
  visitor_ip := coalesce(
    nullif(headers ->> 'cf-connecting-ip', ''),
    nullif(split_part(headers ->> 'x-forwarded-for', ',', 1), ''),
    nullif(headers ->> 'x-real-ip', '')
  );
  if visitor_ip is null then raise exception 'Không xác định được địa chỉ người dùng.'; end if;
  return encode(extensions.digest(trim(visitor_ip) || ':onmyoji-review-like-v1', 'sha256'), 'hex');
end;
$$;

create or replace function public.like_shikigami_review(p_review_id bigint)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
declare inserted_count integer;
begin
  if not exists (select 1 from public.shikigami_reviews where id = p_review_id and status = 'approved') then
    raise exception 'Đánh giá chưa được duyệt.';
  end if;
  insert into public.shikigami_review_likes (review_id, voter_hash)
  values (p_review_id, public.review_like_visitor_hash())
  on conflict do nothing;
  get diagnostics inserted_count = row_count;
  return inserted_count = 1;
end;
$$;

create or replace function public.get_approved_shikigami_reviews(p_shikigami_id integer)
returns table (
  id bigint, shikigami_id integer, user_id uuid, category text, rating smallint, content text,
  reviewer_name text, verdict text, summary text,
  pve_short_score numeric, pve_short_note text, pve_long_score numeric, pve_long_note text,
  pvp_score numeric, pvp_note text, beginner_score numeric, beginner_note text,
  strengths text, weaknesses text, pve_review text, pvp_review text, soul_recommendations text,
  status text, created_at timestamptz, updated_at timestamptz,
  like_count bigint, viewer_liked boolean
)
language sql
security definer
set search_path = public, extensions
as $$
  select r.id, r.shikigami_id, r.user_id, r.category, r.rating, r.content,
    r.reviewer_name, r.verdict, r.summary,
    r.pve_short_score, r.pve_short_note, r.pve_long_score, r.pve_long_note,
    r.pvp_score, r.pvp_note, r.beginner_score, r.beginner_note,
    r.strengths, r.weaknesses, r.pve_review, r.pvp_review, r.soul_recommendations,
    r.status, r.created_at, r.updated_at,
    count(l.id)::bigint as like_count,
    coalesce(bool_or(l.voter_hash = public.review_like_visitor_hash()), false) as viewer_liked
  from public.shikigami_reviews r
  left join public.shikigami_review_likes l on l.review_id = r.id
  where r.shikigami_id = p_shikigami_id and r.status = 'approved'
  group by r.id
  order by count(l.id) desc, r.created_at desc;
$$;

revoke all on function public.review_like_visitor_hash() from public;
grant execute on function public.like_shikigami_review(bigint) to anon, authenticated;
grant execute on function public.get_approved_shikigami_reviews(integer) to anon, authenticated;

drop policy if exists "visitors submit pending reviews" on public.shikigami_reviews;
create policy "visitors submit pending reviews" on public.shikigami_reviews
for insert to anon, authenticated
with check (
  status = 'pending'
  and reviewer_name is not null
  and char_length(trim(reviewer_name)) >= 2
  and verdict is not null
  and char_length(trim(verdict)) >= 3
  and (user_id is null or (select auth.uid()) = user_id)
);
